### PR TITLE
EZS-796 A clean install adds "random" policies to new roles

### PR DESCRIPTION
**Pull request by kamilmusial**
JIRA: http://jira.ez.no/browse/EZS-796

### CODE REVIEW

**Comment by kamilmusial** [comment]
ping @Nattfarinn @clash82

**Comment by andrerom** [comment]
Why is there content in the tables already?

**Comment by kamilmusial** [comment]
Because this installer extends Platform's to not duplicate basic data.

**Comment by andrerom** [comment]
ok, but is the problem in Platform? hence is this a workaround just for studio which does not solve the root issue?

**Comment by andrerom** [comment]
And why is this happening, there is no explanation here or on the issue, this is a must to be able to review ;)

**Comment by kamilmusial** [comment]
Yup. I agree and will provide a feedback. But that issue was a good opportunity to clean roles and policies in clean studio install :)

**Comment by andrerom** [comment]
> Yup. I agree and will provide a feedback. But that issue was a good opportunity to clean roles and policies in clean studio install :)

sure, but that means platform and studio clean data, the once supposed to be used to install, and the once we need to take into account when updating from platform to studio and back, is further diverging.

**Comment by kamilmusial** [comment]
But this is clean installer, not updater, so the result of this sql should be a Platform with landing page content type + basic roles. That's the main reason why I extended Platform Installer, not created the similar as demo.

Updater should be more complex and - as you said - cover studio uninstall as well.

BTW, the problem occurs only in Studio, Platform works well. I'll find out why when there will be more time before release.

**Comment by andrerom** [comment]
> But this is clean installer, not updater, so the result of this sql should be a Platform with landing page content type + basic roles. That's the main reason why I extended Platform Installer, not created the similar as demo.

I was implying that more differences between platform clean and studio clean will mean migration from platform to studio becomes more complex. And doc will differ as well as it now will be missing Editor and Member role in Studio, but not platform. :)

**Comment by kamilmusial** [comment]
True, I misunderstood your comment.

**Comment by lserwatka** [comment]
-1

As we discussed @kamilmusial we should rather find out why this happening in the eZ Studio and correct SQL so that we can re-use what is in the eZ Platform.

**Pull request closed without merging**
