### PR TITLE
IBX-153: Added indices to workflow relation to optimize queries

### PR DESCRIPTION
**Pull request by adamwojs**
> JIRA: https://issues.ibexa.co/browse/IBX-153

### Description

Added missing indexes to `ezeditorialworkflow_workflows` table. See https://github.com/ezsystems/ezplatform-workflow/pull/181

### Upgrade 

Upgrade script as PR target is `2.5`

```sql
CREATE INDEX idx_workflow_co_id_ver ON ezeditorialworkflow_workflows(content_id, version_no);
CREATE INDEX idx_workflow_name ON ezeditorialworkflow_workflows(workflow_name);
```

### CODE REVIEW

**Review by ViniTou — APPROVED** [review]

**Review by alongosz — CHANGES_REQUESTED** [review]
The proper commit title could be `IBX-153: Added indices to workflow relation to optimize queries`. Changed PR title, but it's gonna be merged using commit title as it's the only one commit.

**Review by tomaszszopinski — APPROVED** [review]
QA approved on eZPlatform 2.5-dev.

**Comment by lserwatka** [comment]
Could you merge it up?

**Comment by adamwojs** [comment]
Done.

**Pull request merged**
