### PR TITLE
EZEE-1922: Moving content located under 'eZ Platform' folder doesn't update ezcontentobject_tree.depth value

### PR DESCRIPTION
**Pull request by konradoboza**
> JIRA: https://jira.ez.no/browse/EZEE-1922

This PR fixes value for `depth` field in `ezcontentobject_tree` table for studio-clean installation sql.

### CODE REVIEW

**Comment by konradoboza** [comment]
ping @damianz5 @ViniTou @webhdx

**Review by damianz5 — APPROVED** [review]

**Review by jacek-foremski — APPROVED** [review]

**Review by webhdx — APPROVED** [review]

**Review by ViniTou — APPROVED** [review]

**Comment by konradoboza** [comment]
ping @micszo

**Review by micszo — APPROVED** [review]
Retest OK on eZ Platform EE v1.13.2-rc1 (v.1.5.1) with diff.

**Comment by konradoboza** [comment]
@lserwatka seems to be ready to merge.

**Comment by lserwatka** [comment]
thank you @konradoboza

**Pull request merged**
