### PR TITLE
EZEE-2534: Fix forms depth value in installer's sql - UDW tree is not loaded properly for Forms folder

### PR DESCRIPTION
**Pull request by tischsoic**
JIRA: https://jira.ez.no/browse/EZEE-2534

### CODE REVIEW

**Review by alongosz — APPROVED** [review]

**Review by adamwojs — APPROVED** [review]

**Review by micszo — APPROVED** [review]
Retest successful on eZ Platform EE v2.4.2.

**Comment by lserwatka** [comment]
@tischsoic you can merge it up.

**Comment by tischsoic** [comment]
Merged up:
- master: https://github.com/ezsystems/ezplatform-ee-installer/commit/ba82c2494de988e9ad65809fc6fa865f287f27dc

**Comment by alongosz** [comment]
> * master: [ba82c24](https://github.com/ezsystems/ezplatform-ee-installer/commit/ba82c2494de988e9ad65809fc6fa865f287f27dc)

Well done @tischsoic :tada:

**Pull request merged**
